'use client';

import React, { useState } from 'react';
import { Library, FileText, Search, Plus, Edit3, ChevronRight, X, Save } from 'lucide-react';

interface WikiPage {
  id: string;
  title: string;
  category: string;
  updated: string;
  content: string;
}

export default function KnowledgeBasePage() {
  const [pages, setPages] = useState<WikiPage[]>([
    {
      id: 'page-1',
      title: 'Persona OS Master Operational Handbook 2026',
      category: 'Agency Operations',
      updated: '2026-07-21',
      content: `# Persona OS Master Operational Handbook

Welcome to the official internal wiki for Persona OS creative agency operations.

## Core Rules & Master Calculations

1. **Working Capacity**: 6 effective hours/day × 5 days/week × 4 weeks/month = **120 working hours / month**.
2. **Standard Hourly Point**: 1 hour = **100 points**. Monthly capacity = **12,000 points**.
3. **Financial COGS**: 1 point = **Rp 250**.
4. **Auto-Deadline Rule**: Posting Date minus 3 working days (\`Posting Date - 3 days\`).

## Permanent Client Budget Allocation
- **Baking Empire Gading Serpong**: 5,000 pts (Rp 1.25M COGS)
- **Baking Empire Kelapa Gading**: 3,000 pts (Rp 750k COGS)
- **Baking Empire Citra 8**: 5,000 pts (Rp 1.25M COGS)
- **Samazama Japan**: 5,000 pts (Rp 1.25M COGS)
- **Karihome**: 5,667 pts (Rp 1.41M COGS)
- **MotoDW**: 19,533 pts (Rp 4.88M COGS)`,
    },
    {
      id: 'page-2',
      title: '19 Master Score Rule Definitions',
      category: 'Score System',
      updated: '2026-07-20',
      content: `# 19 Master Score Standard Rules

Every creative asset generated by team members is scored according to approved complexity standards:

- **Editing Reels / TikTok 4K**: 150 points
- **Editing Carousel Graphic**: 150 points
- **Single Foto Retouching**: 10 points
- **Grafis Banner / Announcement**: 25 points
- **Story Video**: 33 points
- **Production Lead (4 Hours Shoot)**: 400 points
- **Production Lead (8 Hours Shoot)**: 800 points
- **Strategic Content Plan (4 Hours)**: 400 points
- **Scheduling (Per Post)**: 5 points
- **Minor Revision**: 10 points`,
    },
  ]);

  const [activePageId, setActivePageId] = useState<string>('page-1');
  const [searchQuery, setSearchQuery] = useState<string>('');

  // Modals state
  const [isAddModalOpen, setIsAddModalOpen] = useState<boolean>(false);
  const [isEditModalOpen, setIsEditModalOpen] = useState<boolean>(false);

  // Form states
  const [newTitle, setNewTitle] = useState<string>('');
  const [newCategory, setNewCategory] = useState<string>('Standard Operating Procedure');
  const [newContent, setNewContent] = useState<string>('');

  const [editTitle, setEditTitle] = useState<string>('');
  const [editCategory, setEditCategory] = useState<string>('');
  const [editContent, setEditContent] = useState<string>('');

  const activePage = pages.find((p) => p.id === activePageId) || pages[0];

  const filteredPages = pages.filter(
    (p) =>
      p.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      p.category.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const handleCreatePage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;

    const newPage: WikiPage = {
      id: `page-${Date.now()}`,
      title: newTitle.trim(),
      category: newCategory,
      updated: new Date().toISOString().split('T')[0],
      content: newContent || `# ${newTitle}\n\nWrite documentation here...`,
    };

    setPages((prev) => [...prev, newPage]);
    setActivePageId(newPage.id);
    setNewTitle('');
    setNewContent('');
    setIsAddModalOpen(false);
  };

  const openEditModal = () => {
    if (!activePage) return;
    setEditTitle(activePage.title);
    setEditCategory(activePage.category);
    setEditContent(activePage.content);
    setIsEditModalOpen(true);
  };

  const handleUpdatePage = (e: React.FormEvent) => {
    e.preventDefault();
    if (!activePage) return;

    setPages((prev) =>
      prev.map((p) =>
        p.id === activePage.id
          ? {
              ...p,
              title: editTitle,
              category: editCategory,
              content: editContent,
              updated: new Date().toISOString().split('T')[0],
            }
          : p
      )
    );

    setIsEditModalOpen(false);
  };

  return (
    <div className="space-y-6 animate-fadeIn text-neutral-900">
      {/* Header & Action Buttons */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold tracking-tight text-neutral-900 flex items-center gap-2">
            Internal Knowledge Base <span className="text-xs font-mono bg-neutral-100 text-neutral-600 px-2.5 py-0.5 rounded-full border border-neutral-200">{pages.length} Documents</span>
          </h1>
          <p className="text-xs text-neutral-500">
            Internal company wiki, operational handbooks, score rule definitions, and technical guidelines.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsAddModalOpen(true)}
            className="bg-neutral-900 hover:bg-neutral-800 text-white text-xs font-semibold px-4 py-2 rounded-lg shadow-xs flex items-center gap-2 transition"
          >
            <Plus className="w-4 h-4" /> New Wiki Page
          </button>
        </div>
      </div>

      {/* Main Workspace Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Left Sidebar Pages Tree */}
        <div className="p-4 rounded-2xl bg-white border border-neutral-200/80 shadow-xs space-y-4">
          <div className="flex items-center justify-between pb-2 border-b border-neutral-100">
            <span className="text-xs font-semibold text-neutral-500 uppercase tracking-wider flex items-center gap-1.5">
              <Library className="w-4 h-4 text-neutral-700" /> Wiki Navigation
            </span>
          </div>

          <div className="flex items-center gap-2 bg-neutral-50 px-3 py-1.5 rounded-lg border border-neutral-200 text-xs text-neutral-700">
            <Search className="w-4 h-4 text-neutral-400" />
            <input
              type="text"
              placeholder="Search wiki..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="bg-transparent focus:outline-none w-full placeholder-neutral-400"
            />
          </div>

          <div className="space-y-1 text-xs">
            {filteredPages.map((p) => (
              <button
                key={p.id}
                onClick={() => setActivePageId(p.id)}
                className={`w-full text-left p-2.5 rounded-xl transition flex items-center justify-between ${
                  activePageId === p.id
                    ? 'bg-neutral-100 text-neutral-900 font-semibold border border-neutral-200'
                    : 'text-neutral-600 hover:text-neutral-900 hover:bg-neutral-50'
                }`}
              >
                <div className="flex items-center gap-2 truncate">
                  <FileText className="w-4 h-4 shrink-0 text-neutral-400" />
                  <span className="truncate">{p.title}</span>
                </div>
                <ChevronRight className="w-3.5 h-3.5 shrink-0 text-neutral-400" />
              </button>
            ))}
          </div>
        </div>

        {/* Right Reader Canvas */}
        {activePage && (
          <div className="lg:col-span-3 p-8 rounded-2xl bg-white border border-neutral-200/80 shadow-xs space-y-6">
            <div className="flex items-center justify-between pb-4 border-b border-neutral-100">
              <div>
                <span className="text-[10px] font-mono font-semibold px-2 py-0.5 rounded bg-neutral-100 text-neutral-800 border border-neutral-200">
                  {activePage.category}
                </span>
                <h2 className="text-xl font-bold text-neutral-900 mt-2">{activePage.title}</h2>
              </div>

              <div className="flex items-center gap-3">
                <span className="text-xs font-mono text-neutral-400">Updated {activePage.updated}</span>
                <button
                  onClick={openEditModal}
                  className="bg-white hover:bg-neutral-50 text-neutral-800 text-xs font-semibold px-3 py-1.5 rounded-lg border border-neutral-200 flex items-center gap-1.5 transition shadow-xs"
                >
                  <Edit3 className="w-3.5 h-3.5 text-neutral-600" /> Edit Page
                </button>
              </div>
            </div>

            {/* Markdown Content */}
            <div className="text-xs text-neutral-800 leading-relaxed whitespace-pre-line font-mono bg-neutral-50 p-6 rounded-2xl border border-neutral-200">
              {activePage.content}
            </div>
          </div>
        )}
      </div>

      {/* Modal: New Wiki Page */}
      {isAddModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs">
          <form
            onSubmit={handleCreatePage}
            className="w-full max-w-lg bg-white border border-neutral-200 rounded-2xl shadow-xl p-6 space-y-4 max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between pb-3 border-b border-neutral-100">
              <h3 className="text-base font-bold text-neutral-900 flex items-center gap-2">
                <Plus className="w-4 h-4 text-neutral-700" /> Create New Knowledge Base Page
              </h3>
              <button
                type="button"
                onClick={() => setIsAddModalOpen(false)}
                className="p-1 text-neutral-400 hover:text-neutral-700"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Page Title</label>
                <input
                  type="text"
                  placeholder="e.g. Social Media Content Guidelines..."
                  value={newTitle}
                  onChange={(e) => setNewTitle(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg px-3 py-2 text-neutral-900 focus:outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Category</label>
                <input
                  type="text"
                  placeholder="e.g. Operations, Design, Strategy..."
                  value={newCategory}
                  onChange={(e) => setNewCategory(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg px-3 py-2 text-neutral-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Markdown Content</label>
                <textarea
                  rows={8}
                  placeholder="# Page Title&#10;&#10;Write markdown documentation here..."
                  value={newContent}
                  onChange={(e) => setNewContent(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg p-3 text-neutral-900 focus:outline-none font-mono"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-neutral-100">
              <button
                type="button"
                onClick={() => setIsAddModalOpen(false)}
                className="px-4 py-2 rounded-lg text-xs text-neutral-600 hover:bg-neutral-100"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="bg-neutral-900 hover:bg-neutral-800 text-white font-semibold text-xs px-5 py-2 rounded-lg shadow-xs"
              >
                Publish Wiki Page
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Modal: Edit Wiki Page */}
      {isEditModalOpen && activePage && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-xs">
          <form
            onSubmit={handleUpdatePage}
            className="w-full max-w-xl bg-white border border-neutral-200 rounded-2xl shadow-xl p-6 space-y-4 max-h-[90vh] overflow-y-auto"
          >
            <div className="flex items-center justify-between pb-3 border-b border-neutral-100">
              <h3 className="text-base font-bold text-neutral-900 flex items-center gap-2">
                <Edit3 className="w-4 h-4 text-neutral-700" /> Edit Wiki Page ({activePage.title})
              </h3>
              <button
                type="button"
                onClick={() => setIsEditModalOpen(false)}
                className="p-1 text-neutral-400 hover:text-neutral-700"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="space-y-3 text-xs">
              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Page Title</label>
                <input
                  type="text"
                  value={editTitle}
                  onChange={(e) => setEditTitle(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg px-3 py-2 text-neutral-900 focus:outline-none"
                  required
                />
              </div>

              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Category</label>
                <input
                  type="text"
                  value={editCategory}
                  onChange={(e) => setEditCategory(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg px-3 py-2 text-neutral-900 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-neutral-600 font-semibold mb-1">Markdown Content</label>
                <textarea
                  rows={10}
                  value={editContent}
                  onChange={(e) => setEditContent(e.target.value)}
                  className="w-full bg-white border border-neutral-200 rounded-lg p-3 text-neutral-900 focus:outline-none font-mono"
                />
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 pt-4 border-t border-neutral-100">
              <button
                type="button"
                onClick={() => setIsEditModalOpen(false)}
                className="px-4 py-2 rounded-lg text-xs text-neutral-600 hover:bg-neutral-100"
              >
                Cancel
              </button>
              <button
                type="submit"
                className="bg-neutral-900 hover:bg-neutral-800 text-white font-semibold text-xs px-5 py-2 rounded-lg shadow-xs flex items-center gap-1.5"
              >
                <Save className="w-4 h-4" /> Save Wiki Page
              </button>
            </div>
          </form>
        </div>
      )}
    </div>
  );
}
